# Generated by Django 5.1.7 on 2025-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_file_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='maximum_capacity',
            field=models.FloatField(default=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='used_capacity',
            field=models.FloatField(default=0),
        ),
    ]
