# Generated by Django 5.1.7 on 2025-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_expiration_date_user_subscription_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_plan',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
