# Generated by Django 5.1.7 on 2025-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_user_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
